# Generated by Django 5.1.5 on 2025-02-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_picture_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
    ]
